Completes initial draft of upgrade challenge

diff --git a/instruqt/airgap-embedded/08-deploying-a-new-version/check-jumpbox b/instruqt/airgap-embedded/08-deploying-a-new-version/check-jumpbox
--- a/instruqt/airgap-embedded/08-deploying-a-new-version/check-jumpbox
+++ b/instruqt/airgap-embedded/08-deploying-a-new-version/check-jumpbox
@@ -1,11 +1,18 @@
-#!/bin/sh
-#
-# This script runs when the platform check the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
+#!/usr/bin/env bash
 
-echo "This is the check script"
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
+
+DEPLOYMENT_READY=$(ssh -o StrictHostKeyChecking=no -i /home/replicant/.ssh/id_ed25519 replicant@cluster kubectl --kubeconfig /etc/kubernetes/admin.conf get deployments -o "jsonpath='{.items[?(@.metadata.name == \"kuard\")].status.conditions[?(@.type == \"Available\")].status}'")
+if [[ "${DEPLOYMENT_READY}" != "True" ]] ; then
+  fail-message "Upgraded applicaation not available, please make sure the install has completed"
+  exit 1
+fi
+
+DEPLOYMENT_TAG=$(ssh -o StrictHostKeyChecking=no -i /home/replicant/.ssh/id_ed25519 replicant@cluster kubectl --kubeconfig /etc/kubernetes/admin.conf get deployments -o "jsonpath='{.items[?(@.metadata.name == \"kuard\")].spec.template.spec.containers[?(@.name == \"kuard\")].image}'" | cut -d: -f 2)
+if [[ "${DEPLOYMENT_TAG}" != "green" ]] ; then
+  fail-message "Running application is not the correct version, please make sure you uploaded the new bundle"
+  exit 1
+fi
 
 exit 0
