added analysis steps

diff --git a/instruqt/support-cli/03-collect-support-bundle/check-kubernetes-vm b/instruqt/support-cli/03-collect-support-bundle/check-kubernetes-vm
--- a/instruqt/support-cli/03-collect-support-bundle/check-kubernetes-vm
+++ b/instruqt/support-cli/03-collect-support-bundle/check-kubernetes-vm
@@ -8,4 +8,15 @@
 
 echo "This is the check script"
 
-exit 0
+# Check if nginx pod is in Running state yet
+/usr/local/bin/kubectl get pod | grep nginx | grep Running
+NGINX_POD_STATUS=$?
+echo nginx pod status: $NGINX_POD_STATUS
+# return status of 1 is error, ie not Running state
+if '[' $NGINX_POD_STATUS -eq 1 ']'
+then
+  exit 1
+else
+  exit 0
+fi
+
