Starts modernizing the enterprise preflights lab

diff --git a/instruqt/app-preflights/02-preflight-definition/setup-kubernetes-vm b/instruqt/app-preflights/02-preflight-definition/setup-kubernetes-vm
--- a/instruqt/app-preflights/02-preflight-definition/setup-kubernetes-vm
+++ b/instruqt/app-preflights/02-preflight-definition/setup-kubernetes-vm
@@ -1,11 +1,21 @@
-#!/bin/sh
-#
-# This script runs when the platform setup the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
+#!/usr/bin/env bash
 
-echo "This is the setup script"
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
 
-exit 0
+HOME_DIR=/home/replicant
+
+# Wait for Instruqt bootstrap to be complete
+while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
+do
+  echo "Waiting for Instruqt to finish booting the VM"
+  sleep 1
+done
+
+# convenience library for Replicated lab lifecycle scripts
+source /etc/profile.d/header.sh
+
+agent variable set USERNAME $(get_username)
+agent variable set PASSWORD $(get_password)
+
+
diff --git a/instruqt/app-preflights/03-app-deployment/setup-kubernetes-vm b/instruqt/app-preflights/03-app-deployment/setup-kubernetes-vm
--- a/instruqt/app-preflights/03-app-deployment/setup-kubernetes-vm
+++ b/instruqt/app-preflights/03-app-deployment/setup-kubernetes-vm
@@ -1,11 +1,17 @@
-#!/bin/sh
-#
-# This script runs when the platform setup the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
+#!/usr/bin/env bash
 
-echo "This is the setup script"
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
+
+HOME_DIR=/home/replicant
+
+# convenience library for Replicated lab lifecycle scripts
+source /etc/profile.d/header.sh
+
+# there's only one app created by the automation, so just grab the first in the list
+access_token=$(get_api_token)
+app_slug=$(curl --header 'Accept: application/json' --header "Authorization: ${access_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].slug')
+
+agent variable set REPLICATED_APP ${app_slug}
 
 exit 0
