Makes scripts more consistent for "done" tracks

diff --git a/instruqt/airgap-embedded/02-prepare-your-jumpbox/check-jumpbox b/instruqt/airgap-embedded/02-prepare-your-jumpbox/check-jumpbox
--- a/instruqt/airgap-embedded/02-prepare-your-jumpbox/check-jumpbox
+++ b/instruqt/airgap-embedded/02-prepare-your-jumpbox/check-jumpbox
@@ -1,4 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
 
 # save the session
 tmux capture-pane -t airgap -S -
diff --git a/instruqt/airgap-embedded/03-airgap-deployment-assets/check-jumpbox b/instruqt/airgap-embedded/03-airgap-deployment-assets/check-jumpbox
--- a/instruqt/airgap-embedded/03-airgap-deployment-assets/check-jumpbox
+++ b/instruqt/airgap-embedded/03-airgap-deployment-assets/check-jumpbox
@@ -1,4 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
 
 REPLICANT_HOME=/home/replicant
 
diff --git a/instruqt/airgap-embedded/06-beginning-the-install/check-jumpbox b/instruqt/airgap-embedded/06-beginning-the-install/check-jumpbox
--- a/instruqt/airgap-embedded/06-beginning-the-install/check-jumpbox
+++ b/instruqt/airgap-embedded/06-beginning-the-install/check-jumpbox
@@ -1,10 +1,7 @@
-#!/bin/sh
-#
-# This script runs when the platform check the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
+#!/usr/env/bin bash
+
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
 
 NODE_READY=$(ssh -o StrictHostKeyChecking=no replicant@cluster kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes -o "jsonpath='{.items[0].status.conditions[?(@.type == \"Ready\")].status}'")
 if [[ "${NODE_READY}" != "True" ]] ; then
diff --git a/instruqt/airgap-embedded/06-beginning-the-install/cleanup-jumpbox b/instruqt/airgap-embedded/06-beginning-the-install/cleanup-jumpbox
--- a/instruqt/airgap-embedded/06-beginning-the-install/cleanup-jumpbox
+++ b/instruqt/airgap-embedded/06-beginning-the-install/cleanup-jumpbox
@@ -1,10 +1,7 @@
-#!/bin/sh
-#
-# This script runs when the platform setup the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
+#!/usr/bin/env bash
+
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
 
 # clear the tmux pane and scrollback to look like a fresh shell
 tmux clear-history -t airgap 
