fixes and stuff

diff --git a/instruqt/troubleshoot-training/04-troubleshoot-3/check-cloud-client b/instruqt/troubleshoot-training/04-troubleshoot-3/check-cloud-client
--- a/instruqt/troubleshoot-training/04-troubleshoot-3/check-cloud-client
+++ b/instruqt/troubleshoot-training/04-troubleshoot-3/check-cloud-client
@@ -1,18 +1,27 @@
 #!/bin/bash
 
-service=$(agent variable get T3_SVC_NAME)
-namespace=$(agent variable get T3_SVC_NS)
-port=$(agent variable get T3_SVC_RANDPORT)
+export KUBECONFIG=/opt/kubeconfig
 
-debug-message $service
-debug-message $namespace
-
-targetport=$(kubectl get service -n "${namespace}" "${service}" -o jsonpath='{.spec.ports[0].targetPort}')
-
-debug-message $port
-debug-message $targetport
-
-if [[ "${targetport}" = "${port}" ]]; then
- fail-message "It looks like our service is still broken, check the hints for more information"
- exit 1
+if [[ ! -f /root/solution.yaml ]]; then
+  fail-message "solution.yaml not found in /root/, please create the file and try again"
+  exit 1
 fi
+
+kind=$(yq -r '.kind' /root/solution.yaml)
+
+if [[ ! "$kind" = "Service" ]]; then
+  fail-message "your solution doesn't look correct, you appear to have saved a resource that we weren't expecting"
+  exit 1
+fi
+
+targetPort=$(yq '.spec.ports[0].targetPort' solution.yaml)
+
+if [[ "$targetPort" != "7070" ]]; then
+  fail-message "it looks like your solution is incorrect"
+  exit 1
+fi
+
+kubectl patch service -n default cartservice --type='json' -p='[{"op": "replace", "path": "/spec/ports/0/targetPort", "value": '"7070"'}]'
+
+# restart all app pods
+kubectl delete pods -l "app=frontend"
