Modernizes Support CLI lab

diff --git a/instruqt/support-cli/01-kotsadm-check/setup-kubernetes-vm b/instruqt/support-cli/01-kotsadm-check/setup-kubernetes-vm
--- a/instruqt/support-cli/01-kotsadm-check/setup-kubernetes-vm
+++ b/instruqt/support-cli/01-kotsadm-check/setup-kubernetes-vm
@@ -1,17 +1,24 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
 # This script runs when the platform setup the challenge.
 #
 # The platform determines if the script was successful using the exit code of this
 # script. If the exit code is not 0, the script fails. 
 #
-echo "This is challenge 01 setup script"
 
-#set -eux
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
 
+# convenience library for Replicated lab lifecycle scripts
+source /etc/profile.d/header.sh
 
-# kubernetes k3s is running
-kubectl get nodes 
+## set variables for use in instructions
+# there's only one app created by the automation, so just grab the first in the list
+access_token=$(get_api_token)
+app_slug=$(curl --header 'Accept: application/json' --header "Authorization: ${access_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].slug')
 
-echo "exiting 01-challenge/setup-kubernetes-vm"
+agent variable set USERNAME $(get_username)
+agent variable set PASSWORD $(get_password)
+agent variable set REPLICATED_APP ${app_slug}
+
 exit 0
diff --git a/instruqt/support-cli/02-upload-application-license/setup-kubernetes-vm b/instruqt/support-cli/02-upload-application-license/setup-kubernetes-vm
--- a/instruqt/support-cli/02-upload-application-license/setup-kubernetes-vm
+++ b/instruqt/support-cli/02-upload-application-license/setup-kubernetes-vm
@@ -1,13 +1,16 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
 # This script runs when the platform setup the challenge.
 #
 # The platform determines if the script was successful using the exit code of this
 # script. If the exit code is not 0, the script fails. 
 #
-echo "Starting challenge 02 setup-kubernetes-vm"
 
-#set -eux
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
+
+# convenience library for Replicated lab lifecycle scripts
+source /etc/profile.d/header.sh
 
 # set up troubleshoot deployment blocker files
 # not creating the config.txt so it can be created during execrise
@@ -19,12 +22,20 @@ chmod 400 /etc/support/restraining-bolt.txt
 chmod 400 /etc/support/secretkey.txt
 
 
-# pre-install the kots app
-kubectl kots install support-cli-$INSTRUQT_PARTICIPANT_ID --name support-cli-$INSTRUQT_PARTICIPANT_ID --namespace default --shared-password $INSTRUQT_PARTICIPANT_ID --no-port-forward 
+
+# install the application
+kots_password_base=$(get_password| sha256sum)
+kots_password=${kots_password_base::20}
+kubectl kots install support-cli-$INSTRUQT_PARTICIPANT_ID \
+  --name support-cli-$INSTRUQT_PARTICIPANT_ID \
+  --namespace default \
+  --shared-password ${kots_password} \
+  --no-port-forward
 
 # expose kotsadm
 kubectl expose deployment kotsadm -n $(kubectl get pods -A -l app=kotsadm --no-headers | awk '{ print $1 }' ) --type=LoadBalancer --name=kotsadm-ingress --port=8800 --target-port=3000
 
+# make sure we can access the password in the instructions
+agent variable set KOTS_PASSWORD ${kots_password}
 
-echo "exiting challenge 02 setup-kubernetes-vm"
 exit 0
