Checks for the install

diff --git a/instruqt/avoiding-installation-pitfalls/06-completing-the-install/check-shell b/instruqt/avoiding-installation-pitfalls/06-completing-the-install/check-shell
--- a/instruqt/avoiding-installation-pitfalls/06-completing-the-install/check-shell
+++ b/instruqt/avoiding-installation-pitfalls/06-completing-the-install/check-shell
@@ -1,11 +1,16 @@
-#!/bin/sh
-#
-# This script runs when the platform check the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
+#!/usr/bin/env bash
 
-echo "This is the check script"
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
+source /etc/profile.d/header.sh
 
-exit 0
+result=0
+
+# check for release to Unstable
+installed_chart=$(helm list -o yaml --kubeconfig /home/replicant/.kube/config | yq '.[0].chart')
+if [[ ! "${installed_chart}" == "harbor-16.8.0"  ]] ; then
+  fail-message 'Please be sure to install the Harbor Helm chart'
+  let "result = result + 1"
+fi
+
+exit ${result}
