updates based on internal feedback

diff --git a/lab1-kots/lab1-e2-adding-analyzers/manifests/nginx-deployment.yaml b/lab1-kots/lab1-e2-adding-analyzers/manifests/nginx-deployment.yaml
--- a/lab1-kots/lab1-e2-adding-analyzers/manifests/nginx-deployment.yaml
+++ b/lab1-kots/lab1-e2-adding-analyzers/manifests/nginx-deployment.yaml
@@ -20,11 +20,11 @@ spec:
             - /bin/sh
             - -ec
             - |
-              perms=$(stat -c "%a" /etc/lab1-e3/config.txt)
+              perms=$(stat -c "%a" /etc/lab1-e2/config.txt)
               if [ "$perms" -ne "400" ]; then echo missing config; exit 1; fi
               echo "found config.txt"
           volumeMounts:
-            - mountPath: /etc/lab1-e3
+            - mountPath: /etc/lab1-e2
               name: lab1-config
         - name: check-secret-file
           image: busybox
@@ -32,29 +32,11 @@ spec:
             - /bin/sh
             - -ec
             - |
-              perms=$(stat -c "%a" /etc/lab1-e3/secretkey.txt)
-              if [ "$perms" -ne "400" ]; then echo "missing /etc/lab1-e3/secretkey.txt"; exit 1; fi
+              perms=$(stat -c "%a" /etc/lab1-e2/secretkey.txt)
+              if [ "$perms" -ne "400" ]; then echo "missing /etc/lab1-e2/secretkey.txt"; exit 1; fi
               echo "found secretkey.txt"
           volumeMounts:
-            - mountPath: /etc/lab1-e3
-              name: lab1-config
-        - name: check-restraining-bolt
-          image: kotsadm/kotsadm-operator:v1.33.1
-          command:
-            - /bin/sh
-            - -ec
-            - |
-              while :; do
-                if [ -f /etc/lab1-e3/restrainging-bolt.txt ]; then
-                  echo "restraining bolt found at /etc/lab1-e3/restrainging-bolt.txt, better delete kotsadm"
-                  kubectl delete pod -lapp=kotsadm
-                else
-                  echo "all clear!"
-                  exit 0
-                fi
-              done
-          volumeMounts:
-            - mountPath: /etc/lab1-e3
+            - mountPath: /etc/lab1-e2
               name: lab1-config
       containers:
         - name: nginx
@@ -62,10 +44,17 @@ spec:
           volumeMounts:
             - mountPath: /usr/share/nginx/html
               name: html
+          resources:
+            limits:
+              memory: '256Mi'
+              cpu: '500m'
+            requests:
+              memory: '32Mi'
+              cpu: '100m'
       volumes:
         - name: lab1-config
           hostPath:
-            path: /etc/lab1-e3/
+            path: /etc/lab1-e2/
         - name: html
           configMap:
             name: nginx-html
