Adds solve script for customer preflights test

diff --git a/instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/solve-shell b/instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/solve-shell
--- a/instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/solve-shell
+++ b/instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/solve-shell
@@ -1,11 +1,47 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
+source /etc/profile.d/header.sh
+
+# get the customer id, since it's the password for the Helm installation
+# and users like to copy/paste
+api_token=$(get_api_token)
+app_id=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].id')
+app_slug=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].slug')
+
+# provide an email address for the new customer
+customer_email="${INSTRUQT_PARTICIPANT_ID}@geeglo.io"
+
+# create the new customer and keep track of the ID
+customer_id=$(replicated customer create --name "Geeglo" --email ${customer_email} --channel Stable --expires-in 720h --output json --app ${app_slug} --token ${api_token} | jq -r .id)
+
+# make sure the customer has a trial license
+updated_customer=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" "https://api.replicated.com/vendor/v3/app/${app_id}/customer/${customer_id}" | \
+  jq -c --arg appId "${app_id}" '.customer | {"app_id": $appId, "name": .name, "email": .email, "channel_id": .channels[0].id, "expires_at": .expiresAt, "type": "trial", "is_airgap_enabled": .airgap, "is_gitops_supported": .isGitopsSupported, "is_identity_service_supported": .isIdentityServiceSupported, "is_geoaxis_supported": .isGeoaxisSupported, "is_snapshot_supported": .isSnapshotSupported, "is_support_bundle_upload_enabled": .isSupportBundleUploadEnabled, "entitlementValues":[]}')
+
+# make sure the user has a trial license
+
+# log into the registry as the new customer, use tmux so we do it as
+# the `replicant` user
+
+# get the registry password (which is the license id)
+registry_password=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" "https://api.replicated.com/vendor/v3/app/${app_id}/customer/${customer_id}/license-download" | \
+  yq .spec.licenseID) 
+
+### Assure the tmux session exists
 #
-# This script runs when the platform solve the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
+# In a test scenario Instuqt does not run the user shell for the
+# challenge, which means the tmux session is never established. We
+# need to session for the solve scripts for other challenges to 
+# succeed, so let's create it here.
 #
 
-echo "This is the solve script"
+if ! tmux has-session -t shell ; then
+  tmux new-session -d -s shell su - replicant
+fi
 
-exit 0
+# log in by sending the login sequence to the terminal, the clean up
+tmux send-keys -t shell helm SPACE registry SPACE login SPACE registry.replicated.com SPACE "--username ${customer_email}" SPACE "--password ${registry_password}" ENTER
+tmux send-keys -t shell clear ENTER
+
