Sets up the preflights challenge

diff --git a/instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/setup-shell b/instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/setup-shell
--- a/instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/setup-shell
+++ b/instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/setup-shell
@@ -1,11 +1,44 @@
-#!/bin/sh
-#
-# This script runs when the platform setup the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
+#!/usr/bin/env bash
 
-echo "This is the setup script"
+# This set line ensures that all failures will cause the script to error and exit
+set -euxo pipefail
 
-exit 0
+HOME_DIR=/home/replicant
+
+# Wait for Instruqt bootstrap to be complete
+while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
+do
+  echo "Waiting for Instruqt to finish booting the VM"
+  sleep 1
+done
+
+# convenience library for Replicated lab lifecycle scripts
+source /etc/profile.d/header.sh
+
+# there's only one app created by the automation, so just grab the first in the list
+access_token=$(get_api_token)
+app_slug=$(curl --header 'Accept: application/json' --header "Authorization: ${access_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].slug')
+
+cat <<EMPTY_PREFLIGHT_SECRET > /home/replicant/empty-preflight-secret.yaml
+apiVersion: v1
+kind: Secret
+type: Opaque
+metadata:
+  name: empty-preflights
+stringData:
+  preflights.yaml: |- 
+    apiVersion: troubleshoot.sh/v1beta2
+    kind: Preflight
+    metadata:
+      name: preflight-tutorial
+    spec:
+      analyzers: []
+EMPTY_PREFLIGHT_SECRET
+chown replicant /home/replicant/empty-preflight-secret.yaml
+
+agent variable set USERNAME $(get_username)
+agent variable set PASSWORD $(get_password)
+agent variable set REPLICATED_API_TOKEN ${access_token}
+agent variable set REPLICATED_APP ${app_slug}
+
+
