Adds "Closing the Support Information Gap" lab (#277)
TL;DR
-----

Implements a support lab for the builders experience

Details
-------

Provides a lab that teaches how to suport your customer with the
Replicted Platform builders experience. Takes the learned through
the following steps for their builders plan app:

1. Using Instance Insights to gain situatiional awareness for a
   customer issue.
2. Learning what a support bundle is and how to define and
   collect a simple one.
3. Expanding the support build to be a fairly robust bundle for
   application.
4. Incorporating the support bundle specification into their Helm
   chart.
5. Releasing a new version of the chart containiner the support
   bunlde spec.
6. Upgrading the customer's instance and using the in-cluster
   support bundle spec from the Helm chart to collect a support
   bundle.
7. Making a support bundle definition available from a URI and
   using that to assure an up-to-date support bundle spec
   indepdent of new the application release.

The lab uses the Bitnami chart for the Harbor image registry that
is use in other labs. It includes the changes to the Harbor chart
made in those previous labs. It uses `kubectl rollout pause` and
`kubectl delete pod` to cause a simulated outage.

diff --git a/instruqt/closing-information-gap/track_scripts/setup-shell b/instruqt/closing-information-gap/track_scripts/setup-shell
--- a/instruqt/closing-information-gap/track_scripts/setup-shell
+++ b/instruqt/closing-information-gap/track_scripts/setup-shell
@@ -15,20 +15,29 @@ EOF
 ssh-keygen -t rsa -f /etc/dropbear/dropbear_rsa_host_key -N ''
 
 # use our shared libary in setup scripts
-curl -s -o /etc/profile.d/header.sh https://raw.githubusercontent.com/replicatedhq/kots-field-labs/feature-helm-preflights/libs/header.sh
+curl -s -o /etc/profile.d/header.sh https://raw.githubusercontent.com/replicatedhq/kots-field-labs/feature-information-gap/libs/header.sh
 source /etc/profile.d/header.sh
 
 # change the cluster URI
 yq -i '.clusters[0].cluster.server = "https://cluster:6443"' /home/replicant/.kube/config
 chown -R replicant /home/replicant/.kube
 
-# setup for Vendor Portal access
+## setup for Vendor Portal access
+
 # there's only one app created by the automation, so just grab the first in the list
 api_token=$(get_api_token)
+app_id=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].id')
 app_slug=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].slug')
 export REPLICATED_API_TOKEN=${api_token}
 export REPLICATED_APP=${app_slug}
 
+## convert the application to the builders  experience
+curl  --location "https://api.replicated.com/vendor/v3/app/${app_id}" \
+  --request POST --header 'Accept: application/json' --header "Authorization: ${api_token}" \
+  --header "Content-Type: application/json" \
+  --data '{ "is_foundation": true }'
+
+## release the application with the Replicated SDK
 cd /home/replicant
 mkdir release
 helm pull oci://registry-1.docker.io/bitnamicharts/harbor --untar
@@ -41,7 +50,7 @@ helm dependency update harbor
 # re-package the chart
 helm package harbor --destination release
 
-# release and promote the app with the SDK added
+## release and promote the app with the SDK added
 
 # release to the `Unstable` channel
 replicated release create --promote Unstable --yaml-dir /home/replicant/release --version 16.7.0 \
@@ -68,8 +77,10 @@ replicated channel create --name LTS --description "Releases with long-term supp
 # remove the helm chart we used to create the release
 rm /home/replicant/release/harbor-16.7.0.tgz
 
+## release the application with the Replicated SDK
 # add preflight checks to the Helm chart
-cat <<HARBOR_PREFLIGHTS > /home/replicant/harbor/templates/preflights.yaml
+mkdir /home/replicant/harbor/templates/troubleshoot
+cat <<HARBOR_PREFLIGHTS > /home/replicant/harbor/templates/troubleshoot/preflights.yaml
 apiVersion: v1
 kind: Secret
 metadata:
@@ -155,8 +166,8 @@ HARBOR_PREFLIGHTS
 yq -i '.version = "16.8.0"' /home/replicant/harbor/Chart.yaml
 helm package /home/replicant/harbor --destination /home/replicant/release
 chown -R replicant /home/replicant/harbor /home/replicant/release
-#
-# release and promote the preflight checks added
+
+## release and promote the preflight checks added
 
 # release to the `Unstable` channel
 replicated release create --promote Unstable --yaml-dir /home/replicant/release --version 16.8.0 \
@@ -176,12 +187,48 @@ replicated release promote ${release_sequence} Stable --version 16.8.0 \
   --release-notes "Adds preflight checks to enable customers to validate cluster prerequisites before installing" \
   --app ${app_slug} --token ${api_token}
 
-# create LTS channel from the "distributing" lab so things look consistent
-replicated channel create --name LTS --description "Releases with long-term support available" \
-  --app ${app_slug} --token ${api_token}
-
 # remove the helm chart we used to create the release
 rm /home/replicant/release/harbor-16.8.0.tgz
+
+## create the customer from the preflights lab
+
+# provide an email address for the new customer
+customer_email="${INSTRUQT_PARTICIPANT_ID}@geeglo.io"
+
+# create the new customer and keep track of the ID
+customer_id=$(replicated customer create --name "Geeglo" --email ${customer_email} --channel Stable --expires-in 720h --output json --app ${app_slug} --token ${api_token} | jq -r .id)
+
+# make sure the customer has a trial license
+updated_customer=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" "https://api.replicated.com/vendor/v3/app/${app_id}/customer/${customer_id}" | \
+  jq -c --arg appId "${app_id}" '.customer | {"app_id": $appId, "name": .name, "email": .email, "channel_id": .channels[0].id, "expires_at": .expiresAt, "type": "trial", "is_airgap_enabled": .airgap, "is_gitops_supported": .isGitopsSupported, "is_identity_service_supported": .isIdentityServiceSupported, "is_geoaxis_supported": .isGeoaxisSupported, "is_snapshot_supported": .isSnapshotSupported, "is_support_bundle_upload_enabled": .isSupportBundleUploadEnabled, "entitlementValues":[]}')
+
+# make sure the user has a trial license
+
+# log into the registry as the new customer, use tmux so we do it as
+# the `replicant` user
+
+# get the registry password (which is the license id)
+registry_password=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" "https://api.replicated.com/vendor/v3/app/${app_id}/customer/${customer_id}/license-download" | \
+  yq .spec.licenseID)
+ 
+## install the release so we have something to support
+
+# login to the registry
+helm registry login registry.replicated.com \
+  --username ${customer_email} \
+  --password ${registry_password}
+
+# install the application, trying again if it fails since there might be timing issues
+set +e
+retries=0
+while ! helm install harbor --version 16.8.0 \
+  oci://registry.replicated.com/${app_slug}/harbor \
+  --set service.type=NodePort --set service.nodePort.https=30443 \
+  --set externalURL=https://cluster-30443-${INSTRUQT_PARTICIPANT_ID}.env.play.instruqt.com \
+  --kubeconfig /home/replicant/.kube/config && [[ $retries -lt 10 ]]; do
+  sleep 2
+  let "retries = retries + 1"
+done
 
 # make sure permissions are good
 chown -R replicant /home/replicant/harbor /home/replicant/release
